### ISSUE TITLE
Working in ubuntu 20 KDE with some tweaks

### ISSUE THREAD

**Issue by academo** [jeffchannell/gp-okta-linux#2]
hey, thanks a lot for the work you put here

I can confirm this is working in ubuntu 20 with KDE, with a few tweaks:

## Installation
The package `python-requests` is not longer available, therefore the install script fails to install it and exits. I installed it with pip globally and remove that part from the apt command. Note: `python3-requests`  is available, you can also try to use that one.

## Indicator
The indicator works out of the box, very nice work there!
Edit: you need to install the package `gir1.2-appindicator3-0.1` in KDE

## The start.sh script
The start.sh script is instructing openconnect to fake the hipreport and to try to tell the vpn is a windows machine, the VPN I connect to doesn't need this as it has official support for Linux clients, removing that worked for me.

## My system details
```
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.4
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-29-generic
OS Type: 64-bit```


Thanks a lot for the work you put here!

**Comment by qoolqool** [comment]
running on:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```
It works upto eval of gp-saml-gui

then, i have the following error and prevent the VPN connect automatically.
```
Error checking for authorization org.freedesktop.policykit.exec: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
```

Copy and paste the eval output will get the VPN connected


Seems like coredump on polkit
```
polkit.service: Main process exited, code=dumped, status=11/SEGV
```

Update:
Issue solved by adding a sudo in front of pkexec

```
    echo "${COOKIE}" | sudo pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY openconnect \
```
